"""
PORTIA Language Grammar Definition
===================================

This module exports token-class constants plus the revised CFG, FIRST,
FOLLOW, and PREDICT tables consumed by the recursive-descent parser.

250 productions / 117 non-terminals
"""

from __future__ import annotations

from typing import Dict, FrozenSet, Iterable, Tuple


# =========================================================================
# Token-class constants
# =========================================================================
DTYPE_KEYWORDS = frozenset({"int", "long", "float", "double", "char", "string", "bool"})
LITERAL_TYPES = frozenset({"INTLIT", "LONGLIT", "FLOATLIT", "DOUBLELIT", "CHARLIT", "STRINGLIT"})
NUM_LIT_TYPES = frozenset({"INTLIT", "LONGLIT", "FLOATLIT", "DOUBLELIT"})
WHOLE_LIT_TYPES = frozenset({"INTLIT", "LONGLIT"})
REL_OPS = frozenset({"==", "!=", ">", "<", ">=", "<="})
ASSIGN_OPS = frozenset({"=", "+=", "-=", "*=", "/=", "%="})
UPDATE_OPS = frozenset({"+=", "-=", "*=", "/=", "%="})
BOOL_LITERALS = frozenset({"true", "false"})
ADDITIVE_OPS = frozenset({"+", "-"})
MULT_OPS = frozenset({"*", "/", "%"})
BUILTIN_FUNCTIONS = frozenset({"abs", "len", "pow", "sqrt"})
BUILTIN_FIXED_ARITY = {"abs": 1, "len": 1, "pow": 2, "sqrt": 1}

GRAMMAR_RULE_COUNT = 250
NON_TERMINAL_COUNT = 117


# =========================================================================
# Direct grammar table helpers
# =========================================================================
def _prod(lhs: str, *rhs: str) -> Tuple[str, Tuple[str, ...]]:
    # Store one CFG production as a simple (lhs, rhs tuple) pair.
    return lhs, rhs


def _freeze_named_table(table: Dict[str, Iterable[str]]) -> Dict[str, FrozenSet[str]]:
    # Convert FIRST/FOLLOW entries to frozensets so grammar metadata stays
    # immutable after module import.
    return {key: frozenset(values) for key, values in table.items()}


def _freeze_predict_table(table: Dict[int, Iterable[str]]) -> Dict[int, FrozenSet[str]]:
    # Convert PREDICT entries to frozensets keyed by production number.
    return {key: frozenset(values) for key, values in table.items()}


# =========================================================================
# CFG productions
# =========================================================================
CFG = {
    1: _prod("program", "global_dec", "function", "main_func"),
    2: _prod("global_dec", "global", "mutability", ";", "global_dec"),
    3: _prod("global_dec", "weave_def", "global_dec"),
    4: _prod("global_dec"),
    5: _prod("mutability", "var", "var_or_weave"),
    6: _prod("mutability", "const", "const_weave"),
    7: _prod("var_or_weave", "dtype", "id", "var_or_arr"),
    8: _prod("var_or_weave", "id", "id", "=", "{", "weave_init_list", "}"),
    9: _prod("const_weave", "dtype", "id", "const_or_arr"),
    10: _prod("const_weave", "id", "id", "=", "{", "weave_init_list", "}"),
    11: _prod("dtype", "int"),
    12: _prod("dtype", "long"),
    13: _prod("dtype", "float"),
    14: _prod("dtype", "double"),
    15: _prod("dtype", "char"),
    16: _prod("dtype", "string"),
    17: _prod("dtype", "bool"),
    18: _prod("var_or_arr", "=", "value", "multi_dec"),
    19: _prod("var_or_arr", "[", "size", "]", "var_1D_or_2D"),
    20: _prod("const_or_arr", "=", "literals_num", "multi_dec_const"),
    21: _prod("const_or_arr", "[", "size", "]", "const_1D_or_2D"),
    22: _prod("value", "string_or_logical_expr"),
    23: _prod("multi_dec", ",", "id", "=", "value", "multi_dec"),
    24: _prod("multi_dec"),
    25: _prod("multi_dec_const", ",", "id", "=", "literals_num", "multi_dec_const"),
    26: _prod("multi_dec_const"),
    27: _prod("size", "intlit"),
    28: _prod("size", "id"),
    29: _prod("literals_num", "literals"),
    30: _prod("literals_num", "-", "num_lit"),
    31: _prod("num_lit", "intlit"),
    32: _prod("num_lit", "longlit"),
    33: _prod("num_lit", "floatlit"),
    34: _prod("num_lit", "doublelit"),
    35: _prod("var_1D_or_2D", "=", "{", "1D_elem_list", "}"),
    36: _prod("var_1D_or_2D", "[", "size", "]", "arr_2D_init_opt"),
    37: _prod("var_1D_or_2D"),
    38: _prod("1D_elem_list", "elem_value", "1D_elem_list_tail"),
    39: _prod("elem_value", "literals"),
    40: _prod("elem_value", "id"),
    41: _prod("1D_elem_list_tail", ",", "elem_value", "1D_elem_list_tail"),
    42: _prod("1D_elem_list_tail"),
    43: _prod("arr_2D_init_opt", "arr_2D_init"),
    44: _prod("arr_2D_init_opt"),
    45: _prod("arr_2D_init", "=", "{", "2D_elem_list", "}"),
    46: _prod("2D_elem_list", "{", "1D_elem_list", "}", "2D_elem_list_cont"),
    47: _prod("2D_elem_list_cont", ",", "2D_elem_list"),
    48: _prod("2D_elem_list_cont"),
    49: _prod("const_1D_or_2D", "=", "{", "1D_elem_list", "}"),
    50: _prod("const_1D_or_2D", "[", "size", "]", "arr_2D_init"),
    51: _prod("weave_init_list", "weave_elem", "weave_init_list_tail"),
    52: _prod("weave_elem", "literals_num"),
    53: _prod("weave_elem", "id"),
    54: _prod("weave_init_list_tail", ",", "weave_elem", "weave_init_list_tail"),
    55: _prod("weave_init_list_tail"),
    56: _prod("weave_def", "weave", "id", "{", "field_list", "}"),
    57: _prod("field_list", "field_dec", "field_list"),
    58: _prod("field_list"),
    59: _prod("field_dec", "dtype", "id", ";"),
    60: _prod("function", "function_def", "function"),
    61: _prod("function"),
    62: _prod("function_def", "func", "ret_type"),
    63: _prod("ret_type", "dtype", "ret_struct", "id", "(", "param", ")", "{", "function_body", "ret_stmt", "}"),
    64: _prod("ret_type", "void", "id", "(", ")", "{", "function_body", "return", ";", "}"),
    65: _prod("ret_struct", "[", "size", "]", "ret_2D"),
    66: _prod("ret_struct"),
    67: _prod("ret_2D", "[", "size", "]"),
    68: _prod("ret_2D"),
    69: _prod("param", "dtype", "id", "param_struct", "param_tail"),
    70: _prod("param"),
    71: _prod("param_tail", ",", "param"),
    72: _prod("param_tail"),
    73: _prod("param_struct", "[", "size", "]", "param_2D"),
    74: _prod("param_struct"),
    75: _prod("param_2D", "[", "size", "]"),
    76: _prod("param_2D"),
    77: _prod("function_body", "using_block", "local_block", "statement_list"),
    78: _prod("using_block", "using_stmt", ";", "using_block"),
    79: _prod("using_block"),
    80: _prod("using_stmt", "using", "id", "using_cont"),
    81: _prod("using_cont", ",", "id", "using_cont"),
    82: _prod("using_cont"),
    83: _prod("local_block", "local", "mutability", ";", "local_block"),
    84: _prod("local_block"),
    85: _prod("statement_list", "statement", "statement_list"),
    86: _prod("statement_list"),
    87: _prod("statement", "expression", ";"),
    88: _prod("statement", "I/O_stmt"),
    89: _prod("statement", "ctrl_struct"),
    90: _prod("expression", "assign_expr"),
    91: _prod("expression", "builtin_func"),
    92: _prod("assign_expr", "id", "mod_or_call"),
    93: _prod("mod_or_call", "assign_mod_opt", "assign_stmt_op"),
    94: _prod("mod_or_call", "(", "arg", ")"),
    95: _prod("assign_mod_opt", ".", "id"),
    96: _prod("assign_mod_opt", "[", "size_mod", "]", "lhs_index_2d_opt"),
    97: _prod("assign_mod_opt"),
    98: _prod("lhs_index_2d_opt", "[", "size_mod", "]"),
    99: _prod("lhs_index_2d_opt"),
    100: _prod("assign_stmt_op", "=", "value"),
    101: _prod("assign_stmt_op", "+=", "value"),
    102: _prod("assign_stmt_op", "-=", "value"),
    103: _prod("assign_stmt_op", "*=", "value"),
    104: _prod("assign_stmt_op", "/=", "value"),
    105: _prod("assign_stmt_op", "%=", "value"),
    106: _prod("size_mod", "intlit"),
    107: _prod("size_mod", "id"),
    108: _prod("string_or_logical_expr", "logical_expr", "string_expr_tail"),
    109: _prod("string_expr_tail", "..", "logical_expr", "string_expr_tail"),
    110: _prod("string_expr_tail"),
    111: _prod("logical_expr", "logical_term", "logical_expr_tail"),
    112: _prod("logical_expr_tail", "||", "logical_term", "logical_expr_tail"),
    113: _prod("logical_expr_tail"),
    114: _prod("logical_term", "logical_factor", "logical_term_tail"),
    115: _prod("logical_term_tail", "&&", "logical_factor", "logical_term_tail"),
    116: _prod("logical_term_tail"),
    117: _prod("logical_factor", "!", "logical_factor"),
    118: _prod("logical_factor", "rel_expr"),
    119: _prod("rel_expr", "arith_expr", "rel_op", "arith_expr"),
    120: _prod("arith_expr", "term", "add_min_cont"),
    121: _prod("add_min_cont", "+", "term", "add_min_cont"),
    122: _prod("add_min_cont", "-", "term", "add_min_cont"),
    123: _prod("add_min_cont"),
    124: _prod("term", "primary", "mult_div_modulo_cont"),
    125: _prod("mult_div_modulo_cont", "*", "primary", "mult_div_modulo_cont"),
    126: _prod("mult_div_modulo_cont", "/", "primary", "mult_div_modulo_cont"),
    127: _prod("mult_div_modulo_cont", "%", "primary", "mult_div_modulo_cont"),
    128: _prod("mult_div_modulo_cont"),
    129: _prod("primary", "atom"),
    130: _prod("primary", "-", "primary"),
    131: _prod("primary", "(", "cast_or_val"),
    132: _prod("cast_or_val", "dtype", ")", "primary"),
    133: _prod("cast_or_val", "value", ")"),
    134: _prod("atom", "id", "iden_mod"),
    135: _prod("atom", "literals"),
    136: _prod("atom", "builtin_func"),
    137: _prod("iden_mod", "arr_or_func"),
    138: _prod("iden_mod", ".", "id"),
    139: _prod("arr_or_func", "[", "size", "]", "2D_array"),
    140: _prod("arr_or_func", "(", "arg", ")"),
    141: _prod("arr_or_func"),
    142: _prod("2D_array", "[", "size", "]"),
    143: _prod("2D_array"),
    144: _prod("literals", "intlit"),
    145: _prod("literals", "longlit"),
    146: _prod("literals", "floatlit"),
    147: _prod("literals", "doublelit"),
    148: _prod("literals", "charlit"),
    149: _prod("literals", "stringlit"),
    150: _prod("literals", "true"),
    151: _prod("literals", "false"),
    152: _prod("builtin_func", "abs", "(", "value", ")"),
    153: _prod("builtin_func", "len", "(", "value", ")"),
    154: _prod("builtin_func", "pow", "(", "value", ",", "value", ")"),
    155: _prod("builtin_func", "sqrt", "(", "value", ")"),
    156: _prod("arg", "value", "multi_arg"),
    157: _prod("arg"),
    158: _prod("multi_arg", ",", "arg"),
    159: _prod("multi_arg"),
    160: _prod("I/O_stmt", "input_stmt"),
    161: _prod("I/O_stmt", "output_stmt"),
    162: _prod("input_stmt", "trap", "(", "trap_target", ")", ";"),
    163: _prod("trap_target", "id", "trap_suffix"),
    164: _prod("trap_suffix", "[", "size", "]", "2D_array"),
    165: _prod("trap_suffix", ".", "id"),
    166: _prod("trap_suffix"),
    167: _prod("output_stmt", "thread", "(", "print_args", ")", ";"),
    168: _prod("output_stmt", "threadln", "(", "print_args", ")", ";"),
    169: _prod("print_args", "value", "print_tail"),
    170: _prod("print_tail", ",", "value", "print_tail"),
    171: _prod("print_tail"),
    172: _prod("ctrl_struct", "conditional_stmt"),
    173: _prod("ctrl_struct", "loop_stmt"),
    174: _prod("conditional_stmt", "if_stmt"),
    175: _prod("conditional_stmt", "switch_stmt"),
    176: _prod("if_stmt", "if", "(", "condition", ")", "{", "ctrl_body", "ret_ctrl_body", "}", "else_if_ei_stmt"),
    177: _prod("condition", "and_expr", "or_tail"),
    178: _prod("or_tail", "||", "and_expr", "or_tail"),
    179: _prod("or_tail"),
    180: _prod("and_expr", "logical_op", "and_tail"),
    181: _prod("and_tail", "&&", "logical_op", "and_tail"),
    182: _prod("and_tail"),
    183: _prod("logical_op", "!", "logical_op"),
    184: _prod("logical_op", "bool_ctrl"),
    185: _prod("bool_ctrl", "id", "iden_mod", "mult_div_modulo_cont", "add_min_cont", "bool_ctrl_tail"),
    186: _prod("bool_ctrl", "true", "mult_div_modulo_cont", "add_min_cont", "bool_ctrl_tail"),
    187: _prod("bool_ctrl", "false", "mult_div_modulo_cont", "add_min_cont", "bool_ctrl_tail"),
    188: _prod("bool_ctrl", "(", "cast_or_val", "mult_div_modulo_cont", "add_min_cont", "bool_ctrl_tail"),
    189: _prod("bool_ctrl", "cmp_start", "mult_div_modulo_cont", "add_min_cont", "rel_op", "arith_expr"),
    190: _prod("bool_ctrl", "builtin_func", "mult_div_modulo_cont", "add_min_cont", "bool_ctrl_tail"),
    191: _prod("bool_ctrl_tail", "rel_op", "arith_expr"),
    192: _prod("bool_ctrl_tail"),
    193: _prod("cmp_start", "-", "primary"),
    194: _prod("cmp_start", "intlit"),
    195: _prod("cmp_start", "longlit"),
    196: _prod("cmp_start", "floatlit"),
    197: _prod("cmp_start", "doublelit"),
    198: _prod("cmp_start", "charlit"),
    199: _prod("cmp_start", "stringlit"),
    200: _prod("rel_op", "=="),
    201: _prod("rel_op", "!="),
    202: _prod("rel_op", ">"),
    203: _prod("rel_op", "<"),
    204: _prod("rel_op", ">="),
    205: _prod("rel_op", "<="),
    206: _prod("ctrl_body", "local_block", "ctrl_statement_list"),
    207: _prod("ctrl_statement_list", "statement_list", "break_opt"),
    208: _prod("break_opt", "break", ";"),
    209: _prod("break_opt"),
    210: _prod("ret_ctrl_body", "ret_stmt"),
    211: _prod("ret_ctrl_body"),
    212: _prod("else_if_ei_stmt", "else", "else_stmt"),
    213: _prod("else_if_ei_stmt"),
    214: _prod("else_stmt", "if_stmt"),
    215: _prod("else_stmt", "{", "ctrl_body", "ret_ctrl_body", "}"),
    216: _prod("switch_stmt", "switch", "(", "switch_val", ")", "{", "case_list", "default_stmt", "}"),
    217: _prod("case_list", "case_stmt", "case_list"),
    218: _prod("case_list"),
    219: _prod("switch_val", "logical_expr"),
    220: _prod("case_stmt", "case", "case_val", ":", "ctrl_body", "ret_ctrl_body"),
    221: _prod("case_val", "unique_val"),
    222: _prod("unique_val", "charlit"),
    223: _prod("unique_val", "true"),
    224: _prod("unique_val", "false"),
    225: _prod("unique_val", "intlit"),
    226: _prod("unique_val", "longlit"),
    227: _prod("unique_val", "-", "whole_lit"),
    228: _prod("whole_lit", "intlit"),
    229: _prod("whole_lit", "longlit"),
    230: _prod("default_stmt", "default", ":", "ctrl_body", "ret_ctrl_body"),
    231: _prod("default_stmt"),
    232: _prod("loop_stmt", "for_stmt"),
    233: _prod("loop_stmt", "while_stmt"),
    234: _prod("loop_stmt", "do_stmt"),
    235: _prod("for_stmt", "for", "(", "initializer", ";", "condition", ";", "update", ")", "{", "ctrl_body", "ret_ctrl_body", "}"),
    236: _prod("initializer", "local", "var", "dtype", "id", "=", "literals_num"),
    237: _prod("initializer", "id", "=", "literals_num"),
    238: _prod("initializer"),
    239: _prod("update", "id", "update_op", "arith_expr"),
    240: _prod("update"),
    241: _prod("update_op", "+="),
    242: _prod("update_op", "-="),
    243: _prod("update_op", "*="),
    244: _prod("update_op", "/="),
    245: _prod("update_op", "%="),
    246: _prod("while_stmt", "while", "(", "condition", ")", "{", "ctrl_body", "ret_ctrl_body", "}"),
    247: _prod("do_stmt", "do", "{", "ctrl_body", "ret_ctrl_body", "}", "while", "(", "condition", ")", ";"),
    248: _prod("ret_stmt", "return", "value", ";"),
    249: _prod("main_func", "int", "main", "(", ")", "{", "main_body", "}"),
    250: _prod("main_body", "using_block", "local_block", "statement_list", "return", "intlit", ";"),
}


# =========================================================================
# FIRST sets (nullable productions use FOLLOW in the parser)
# =========================================================================
FIRST = _freeze_named_table({
    "program": {"func", "global", "int", "weave"},
    "global_dec": {"global", "weave"},
    "mutability": {"const", "var"},
    "var_or_weave": {"bool", "char", "double", "float", "id", "int", "long", "string"},
    "const_weave": {"bool", "char", "double", "float", "id", "int", "long", "string"},
    "dtype": {"bool", "char", "double", "float", "int", "long", "string"},
    "var_or_arr": {"=", "["},
    "const_or_arr": {"=", "["},
    "value": {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "multi_dec": {","},
    "multi_dec_const": {","},
    "size": {"id", "intlit"},
    "literals_num": {"-", "charlit", "doublelit", "false", "floatlit", "intlit", "longlit", "stringlit", "true"},
    "num_lit": {"doublelit", "floatlit", "intlit", "longlit"},
    "var_1D_or_2D": {"=", "["},
    "1D_elem_list": {"charlit", "doublelit", "false", "floatlit", "id", "intlit", "longlit", "stringlit", "true"},
    "elem_value": {"charlit", "doublelit", "false", "floatlit", "id", "intlit", "longlit", "stringlit", "true"},
    "1D_elem_list_tail": {","},
    "arr_2D_init_opt": {"="},
    "arr_2D_init": {"="},
    "2D_elem_list": {"{"},
    "2D_elem_list_cont": {","},
    "const_1D_or_2D": {"=", "["},
    "weave_init_list": {"-", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "longlit", "stringlit", "true"},
    "weave_elem": {"-", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "longlit", "stringlit", "true"},
    "weave_init_list_tail": {","},
    "weave_def": {"weave"},
    "field_list": {"bool", "char", "double", "float", "int", "long", "string"},
    "field_dec": {"bool", "char", "double", "float", "int", "long", "string"},
    "function": {"func"},
    "function_def": {"func"},
    "ret_type": {"bool", "char", "double", "float", "int", "long", "string", "void"},
    "ret_struct": {"["},
    "ret_2D": {"["},
    "param": {"bool", "char", "double", "float", "int", "long", "string"},
    "param_tail": {","},
    "param_struct": {"["},
    "param_2D": {"["},
    "function_body": {"abs", "do", "for", "id", "if", "len", "local", "pow", "sqrt", "switch", "thread", "threadln", "trap", "using", "while"},
    "using_block": {"using"},
    "using_stmt": {"using"},
    "using_cont": {","},
    "local_block": {"local"},
    "statement_list": {"abs", "do", "for", "id", "if", "len", "pow", "sqrt", "switch", "thread", "threadln", "trap", "while"},
    "statement": {"abs", "do", "for", "id", "if", "len", "pow", "sqrt", "switch", "thread", "threadln", "trap", "while"},
    "expression": {"abs", "id", "len", "pow", "sqrt"},
    "assign_expr": {"id"},
    "mod_or_call": {"%=", "(", "*=", "+=", "-=", ".", "/=", "=", "["},
    "assign_mod_opt": {".", "["},
    "lhs_index_2d_opt": {"["},
    "assign_stmt_op": {"%=", "*=", "+=", "-=", "/=", "="},
    "size_mod": {"id", "intlit"},
    "string_or_logical_expr": {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "string_expr_tail": {".."},
    "logical_expr": {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "logical_expr_tail": {"||"},
    "logical_term": {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "logical_term_tail": {"&&"},
    "logical_factor": {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "rel_expr": {"(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "arith_expr": {"(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "add_min_cont": {"+", "-"},
    "term": {"(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "mult_div_modulo_cont": {"%", "*", "/"},
    "primary": {"(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "cast_or_val": {"!", "(", "-", "abs", "bool", "char", "charlit", "double", "doublelit", "false", "float", "floatlit", "id", "int", "intlit", "len", "long", "longlit", "pow", "sqrt", "string", "stringlit", "true"},
    "atom": {"abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "iden_mod": {"(", ".", "["},
    "arr_or_func": {"(", "["},
    "2D_array": {"["},
    "literals": {"charlit", "doublelit", "false", "floatlit", "intlit", "longlit", "stringlit", "true"},
    "builtin_func": {"abs", "len", "pow", "sqrt"},
    "arg": {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "multi_arg": {","},
    "I/O_stmt": {"thread", "threadln", "trap"},
    "input_stmt": {"trap"},
    "trap_target": {"id"},
    "trap_suffix": {".", "["},
    "output_stmt": {"thread", "threadln"},
    "print_args": {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "print_tail": {","},
    "ctrl_struct": {"do", "for", "if", "switch", "while"},
    "conditional_stmt": {"if", "switch"},
    "if_stmt": {"if"},
    "condition": {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "or_tail": {"||"},
    "and_expr": {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "and_tail": {"&&"},
    "logical_op": {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "bool_ctrl": {"(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "bool_ctrl_tail": {"!=", "<", "<=", "==", ">", ">="},
    "cmp_start": {"-", "charlit", "doublelit", "floatlit", "intlit", "longlit", "stringlit"},
    "rel_op": {"!=", "<", "<=", "==", ">", ">="},
    "ctrl_body": {"abs", "break", "do", "for", "id", "if", "len", "local", "pow", "sqrt", "switch", "thread", "threadln", "trap", "while"},
    "ctrl_statement_list": {"abs", "break", "do", "for", "id", "if", "len", "pow", "sqrt", "switch", "thread", "threadln", "trap", "while"},
    "break_opt": {"break"},
    "ret_ctrl_body": {"return"},
    "else_if_ei_stmt": {"else"},
    "else_stmt": {"if", "{"},
    "switch_stmt": {"switch"},
    "case_list": {"case"},
    "switch_val": {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "case_stmt": {"case"},
    "case_val": {"-", "charlit", "false", "intlit", "longlit", "true"},
    "unique_val": {"-", "charlit", "false", "intlit", "longlit", "true"},
    "whole_lit": {"intlit", "longlit"},
    "default_stmt": {"default"},
    "loop_stmt": {"do", "for", "while"},
    "for_stmt": {"for"},
    "initializer": {"id", "local"},
    "update": {"id"},
    "update_op": {"%=", "*=", "+=", "-=", "/="},
    "while_stmt": {"while"},
    "do_stmt": {"do"},
    "ret_stmt": {"return"},
    "main_func": {"int"},
    "main_body": {"abs", "do", "for", "id", "if", "len", "local", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "using", "while"},
})


# =========================================================================
# FOLLOW sets
# =========================================================================
FOLLOW = _freeze_named_table({
    "program": set(),
    "global_dec": {"func", "int"},
    "mutability": {";"},
    "var_or_weave": {";"},
    "const_weave": {";"},
    "dtype": {")", "[", "id"},
    "var_or_arr": {";"},
    "const_or_arr": {";"},
    "value": {")", ",", ";"},
    "multi_dec": {";"},
    "multi_dec_const": {";"},
    "size": {"]"},
    "literals_num": {",", ";", "}"},
    "num_lit": {",", ";", "}"},
    "var_1D_or_2D": {";"},
    "1D_elem_list": {"}"},
    "elem_value": {",", "}"},
    "1D_elem_list_tail": {"}"},
    "arr_2D_init_opt": {";"},
    "arr_2D_init": {";"},
    "2D_elem_list": {"}"},
    "2D_elem_list_cont": {"}"},
    "const_1D_or_2D": {";"},
    "weave_init_list": {"}"},
    "weave_elem": {",", "}"},
    "weave_init_list_tail": {"}"},
    "weave_def": {"func", "global", "int", "weave"},
    "field_list": {"}"},
    "field_dec": {"bool", "char", "double", "float", "int", "long", "string", "}"},
    "function": {"int"},
    "function_def": {"func", "int"},
    "ret_type": {"func", "int"},
    "ret_struct": {"id"},
    "ret_2D": {"id"},
    "param": {")"},
    "param_tail": {")"},
    "param_struct": {")", ","},
    "param_2D": {")", ","},
    "function_body": {"return"},
    "using_block": {"abs", "do", "for", "id", "if", "len", "local", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while"},
    "using_stmt": {";"},
    "using_cont": {";"},
    "local_block": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "statement_list": {"break", "case", "default", "return", "}"},
    "statement": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "expression": {";"},
    "assign_expr": {";"},
    "mod_or_call": {";"},
    "assign_mod_opt": {"%=", "*=", "+=", "-=", "/=", "="},
    "lhs_index_2d_opt": {"%=", "*=", "+=", "-=", "/=", "="},
    "assign_stmt_op": {";"},
    "size_mod": {"]"},
    "string_or_logical_expr": {")", ",", ";"},
    "string_expr_tail": {")", ",", ";"},
    "logical_expr": {")", ",", "..", ";"},
    "logical_expr_tail": {")", ",", "..", ";"},
    "logical_term": {")", ",", "..", ";", "||"},
    "logical_term_tail": {")", ",", "..", ";", "||"},
    "logical_factor": {"&&", ")", ",", "..", ";", "||"},
    "rel_expr": {"&&", ")", ",", "..", ";", "||"},
    "arith_expr": {"!=", "&&", ")", ",", "..", ";", "<", "<=", "==", ">", ">=", "||"},
    "add_min_cont": {"!=", "&&", ")", ",", "..", ";", "<", "<=", "==", ">", ">=", "||"},
    "term": {"!=", "&&", ")", "+", ",", "-", "..", ";", "<", "<=", "==", ">", ">=", "||"},
    "mult_div_modulo_cont": {"!=", "&&", ")", "+", ",", "-", "..", ";", "<", "<=", "==", ">", ">=", "||"},
    "primary": {"!=", "%", "&&", ")", "*", "+", ",", "-", "..", "/", ";", "<", "<=", "==", ">", ">=", "||"},
    "cast_or_val": {"!=", "%", "&&", ")", "*", "+", ",", "-", "..", "/", ";", "<", "<=", "==", ">", ">=", "||"},
    "atom": {"!=", "%", "&&", ")", "*", "+", ",", "-", "..", "/", ";", "<", "<=", "==", ">", ">=", "||"},
    "iden_mod": {"!=", "%", "&&", ")", "*", "+", ",", "-", "..", "/", ";", "<", "<=", "==", ">", ">=", "||"},
    "arr_or_func": {"!=", "%", "&&", ")", "*", "+", ",", "-", "..", "/", ";", "<", "<=", "==", ">", ">=", "||"},
    "2D_array": {"!=", "%", "&&", ")", "*", "+", ",", "-", "..", "/", ";", "<", "<=", "==", ">", ">=", "||"},
    "literals": {"!=", "%", "&&", ")", "*", "+", ",", "-", "..", "/", ";", "<", "<=", "==", ">", ">=", "||", "}"},
    "builtin_func": {"!=", "%", "&&", ")", "*", "+", ",", "-", "..", "/", ";", "<", "<=", "==", ">", ">=", "||"},
    "arg": {")"},
    "multi_arg": {")"},
    "I/O_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "input_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "trap_target": {")"},
    "trap_suffix": {")"},
    "output_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "print_args": {")"},
    "print_tail": {")"},
    "ctrl_struct": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "conditional_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "if_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "condition": {")", ";"},
    "or_tail": {")", ";"},
    "and_expr": {")", ";", "||"},
    "and_tail": {")", ";", "||"},
    "logical_op": {"&&", ")", ";", "||"},
    "bool_ctrl": set(),
    "bool_ctrl_tail": set(),
    "cmp_start": {"!=", "%", "*", "+", "-", "/", "<", "<=", "==", ">", ">="},
    "rel_op": {"(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "ctrl_body": {"case", "default", "return", "}"},
    "ctrl_statement_list": {"case", "default", "return", "}"},
    "break_opt": {"case", "default", "return", "}"},
    "ret_ctrl_body": {"case", "default", "}"},
    "else_if_ei_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "else_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "switch_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "case_list": {"default", "}"},
    "switch_val": {")"},
    "case_stmt": {"case", "default", "}"},
    "case_val": {":"},
    "unique_val": {":"},
    "whole_lit": {":"},
    "default_stmt": {"}"},
    "loop_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "for_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "initializer": {";"},
    "update": {")"},
    "update_op": {"(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "while_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "do_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "ret_stmt": {"case", "default", "}"},
    "main_func": set(),
    "main_body": {"}"},
})


# =========================================================================
# PREDICT sets keyed by production number
# =========================================================================
PREDICT = _freeze_predict_table({
    1: {"int", "func", "global", "weave"},
    2: {"global"},
    3: {"weave"},
    4: {"int", "func"},
    5: {"var"},
    6: {"const"},
    7: {"int", "bool", "char", "double", "float", "long", "string"},
    8: {"id"},
    9: {"int", "bool", "char", "double", "float", "long", "string"},
    10: {"id"},
    11: {"int"},
    12: {"long"},
    13: {"float"},
    14: {"double"},
    15: {"char"},
    16: {"string"},
    17: {"bool"},
    18: {"="},
    19: {"["},
    20: {"="},
    21: {"["},
    22: {"!", "-", "(", "id", "abs", "charlit", "doublelit", "false", "floatlit", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    23: {","},
    24: {";"},
    25: {","},
    26: {";"},
    27: {"intlit"},
    28: {"id"},
    29: {"charlit", "doublelit", "false", "floatlit", "intlit", "longlit", "stringlit", "true"},
    30: {"-"},
    31: {"intlit"},
    32: {"longlit"},
    33: {"floatlit"},
    34: {"doublelit"},
    35: {"="},
    36: {"["},
    37: {";"},
    38: {"id", "charlit", "doublelit", "false", "floatlit", "intlit", "longlit", "stringlit", "true"},
    39: {"charlit", "doublelit", "false", "floatlit", "intlit", "longlit", "stringlit", "true"},
    40: {"id"},
    41: {","},
    42: {"}"},
    43: {"="},
    44: {";"},
    45: {"="},
    46: {"{"},
    47: {","},
    48: {"}"},
    49: {"="},
    50: {"["},
    51: {"-", "id", "charlit", "doublelit", "false", "floatlit", "intlit", "longlit", "stringlit", "true"},
    52: {"-", "charlit", "doublelit", "false", "floatlit", "intlit", "longlit", "stringlit", "true"},
    53: {"id"},
    54: {","},
    55: {"}"},
    56: {"weave"},
    57: {"int", "bool", "char", "double", "float", "long", "string"},
    58: {"}"},
    59: {"int", "bool", "char", "double", "float", "long", "string"},
    60: {"func"},
    61: {"int"},
    62: {"func"},
    63: {"int", "bool", "char", "double", "float", "long", "string"},
    64: {"void"},
    65: {"["},
    66: {"id"},
    67: {"["},
    68: {"id"},
    69: {"int", "bool", "char", "double", "float", "long", "string"},
    70: {")"},
    71: {","},
    72: {")"},
    73: {"["},
    74: {",", ")"},
    75: {"["},
    76: {",", ")"},
    77: {"id", "local", "using", "return", "abs", "do", "for", "if", "len", "pow", "sqrt", "switch", "thread", "threadln", "trap", "while"},
    78: {"using"},
    79: {"id", "local", "return", "abs", "do", "for", "if", "len", "pow", "sqrt", "switch", "thread", "threadln", "trap", "while"},
    80: {"using"},
    81: {","},
    82: {";"},
    83: {"local"},
    84: {"}", "id", "return", "abs", "break", "case", "default", "do", "for", "if", "len", "pow", "sqrt", "switch", "thread", "threadln", "trap", "while"},
    85: {"id", "abs", "do", "for", "if", "len", "pow", "sqrt", "switch", "thread", "threadln", "trap", "while"},
    86: {"}", "return", "break", "case", "default"},
    87: {"id", "abs", "len", "pow", "sqrt"},
    88: {"thread", "threadln", "trap"},
    89: {"do", "for", "if", "switch", "while"},
    90: {"id"},
    91: {"abs", "len", "pow", "sqrt"},
    92: {"id"},
    93: {"=", "[", "%=", "*=", "+=", "-=", ".", "/="},
    94: {"("},
    95: {"."},
    96: {"["},
    97: {"=", "%=", "*=", "+=", "-=", "/="},
    98: {"["},
    99: {"=", "%=", "*=", "+=", "-=", "/="},
    100: {"="},
    101: {"+="},
    102: {"-="},
    103: {"*="},
    104: {"/="},
    105: {"%="},
    106: {"intlit"},
    107: {"id"},
    108: {"!", "-", "(", "id", "abs", "charlit", "doublelit", "false", "floatlit", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    109: {".."},
    110: {",", ";", ")"},
    111: {"!", "-", "(", "id", "abs", "charlit", "doublelit", "false", "floatlit", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    112: {"||"},
    113: {",", ";", ")", ".."},
    114: {"!", "-", "(", "id", "abs", "charlit", "doublelit", "false", "floatlit", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    115: {"&&"},
    116: {",", ";", ")", "..", "||"},
    117: {"!"},
    118: {"-", "(", "id", "abs", "charlit", "doublelit", "false", "floatlit", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    119: {"-", "(", "id", "abs", "charlit", "doublelit", "false", "floatlit", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    120: {"-", "(", "id", "abs", "charlit", "doublelit", "false", "floatlit", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    121: {"+"},
    122: {"-"},
    123: {",", ";", ")", "!=", "&&", "..", "<", "<=", "==", ">", ">=", "||"},
    124: {"-", "(", "id", "abs", "charlit", "doublelit", "false", "floatlit", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    125: {"*"},
    126: {"/"},
    127: {"%"},
    128: {",", ";", ")", "-", "!=", "&&", "+", "..", "<", "<=", "==", ">", ">=", "||"},
    129: {"id", "abs", "charlit", "doublelit", "false", "floatlit", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    130: {"-"},
    131: {"("},
    132: {"int", "bool", "char", "double", "float", "long", "string"},
    133: {"!", "-", "(", "id", "abs", "charlit", "doublelit", "false", "floatlit", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    134: {"id"},
    135: {"charlit", "doublelit", "false", "floatlit", "intlit", "longlit", "stringlit", "true"},
    136: {"abs", "len", "pow", "sqrt"},
    137: {",", ";", ")", "[", "-", "(", "!=", "%", "&&", "*", "+", "..", "/", "<", "<=", "==", ">", ">=", "||"},
    138: {"."},
    139: {"["},
    140: {"("},
    141: {",", ";", ")", "-", "!=", "%", "&&", "*", "+", "..", "/", "<", "<=", "==", ">", ">=", "||"},
    142: {"["},
    143: {",", ";", ")", "-", "!=", "%", "&&", "*", "+", "..", "/", "<", "<=", "==", ">", ">=", "||"},
    144: {"intlit"},
    145: {"longlit"},
    146: {"floatlit"},
    147: {"doublelit"},
    148: {"charlit"},
    149: {"stringlit"},
    150: {"true"},
    151: {"false"},
    152: {"abs"},
    153: {"len"},
    154: {"pow"},
    155: {"sqrt"},
    156: {"!", "-", "(", "id", "abs", "charlit", "doublelit", "false", "floatlit", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    157: {")"},
    158: {","},
    159: {")"},
    160: {"trap"},
    161: {"thread", "threadln"},
    162: {"trap"},
    163: {"id"},
    164: {"["},
    165: {"."},
    166: {")"},
    167: {"thread"},
    168: {"threadln"},
    169: {"!", "-", "(", "id", "abs", "charlit", "doublelit", "false", "floatlit", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    170: {","},
    171: {")"},
    172: {"if", "switch"},
    173: {"do", "for", "while"},
    174: {"if"},
    175: {"switch"},
    176: {"if"},
    177: {"!", "-", "(", "id", "abs", "charlit", "doublelit", "false", "floatlit", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    178: {"||"},
    179: {";", ")"},
    180: {"!", "-", "(", "id", "abs", "charlit", "doublelit", "false", "floatlit", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    181: {"&&"},
    182: {";", ")", "||"},
    183: {"!"},
    184: {"-", "(", "id", "abs", "charlit", "doublelit", "false", "floatlit", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    185: {"id"},
    186: {"true"},
    187: {"false"},
    188: {"("},
    189: {"-", "charlit", "doublelit", "floatlit", "intlit", "longlit", "stringlit"},
    190: {"abs", "len", "pow", "sqrt"},
    191: {"!=", "<", "<=", "==", ">", ">="},
    192: {},
    193: {"-"},
    194: {"intlit"},
    195: {"longlit"},
    196: {"floatlit"},
    197: {"doublelit"},
    198: {"charlit"},
    199: {"stringlit"},
    200: {"=="},
    201: {"!="},
    202: {">"},
    203: {"<"},
    204: {">="},
    205: {"<="},
    206: {"}", "id", "local", "return", "abs", "break", "case", "default", "do", "for", "if", "len", "pow", "sqrt", "switch", "thread", "threadln", "trap", "while"},
    207: {"}", "id", "return", "abs", "break", "case", "default", "do", "for", "if", "len", "pow", "sqrt", "switch", "thread", "threadln", "trap", "while"},
    208: {"break"},
    209: {"}", "return", "case", "default"},
    210: {"return"},
    211: {"}", "case", "default"},
    212: {"else"},
    213: {"}", "id", "return", "abs", "break", "case", "default", "do", "for", "if", "len", "pow", "sqrt", "switch", "thread", "threadln", "trap", "while"},
    214: {"if"},
    215: {"{"},
    216: {"switch"},
    217: {"case"},
    218: {"}", "default"},
    219: {"!", "-", "(", "id", "abs", "charlit", "doublelit", "false", "floatlit", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    220: {"case"},
    221: {"-", "charlit", "false", "intlit", "longlit", "true"},
    222: {"charlit"},
    223: {"true"},
    224: {"false"},
    225: {"intlit"},
    226: {"longlit"},
    227: {"-"},
    228: {"intlit"},
    229: {"longlit"},
    230: {"default"},
    231: {"}"},
    232: {"for"},
    233: {"while"},
    234: {"do"},
    235: {"for"},
    236: {"local"},
    237: {"id"},
    238: {";"},
    239: {"id"},
    240: {")"},
    241: {"+="},
    242: {"-="},
    243: {"*="},
    244: {"/="},
    245: {"%="},
    246: {"while"},
    247: {"do"},
    248: {"return"},
    249: {"int"},
    250: {"id", "local", "using", "return", "abs", "do", "for", "if", "len", "pow", "sqrt", "switch", "thread", "threadln", "trap", "while"},
})


def _validate_tables() -> None:
    if len(CFG) != GRAMMAR_RULE_COUNT:
        raise RuntimeError(
            f"Expected {GRAMMAR_RULE_COUNT} CFG productions, found {len(CFG)}"
        )
    if len(FIRST) != NON_TERMINAL_COUNT:
        raise RuntimeError(
            f"Expected {NON_TERMINAL_COUNT} FIRST-set entries, found {len(FIRST)}"
        )
    if len(FOLLOW) != NON_TERMINAL_COUNT:
        raise RuntimeError(
            f"Expected {NON_TERMINAL_COUNT} FOLLOW-set entries, found {len(FOLLOW)}"
        )
    if set(FIRST) != set(FOLLOW):
        raise RuntimeError("FIRST and FOLLOW tables do not cover the same non-terminals")
    if len(PREDICT) != GRAMMAR_RULE_COUNT:
        raise RuntimeError(
            f"Expected {GRAMMAR_RULE_COUNT} PREDICT-set entries, found {len(PREDICT)}"
        )

    required_first_memberships = {
        "builtin_func": BUILTIN_FUNCTIONS,
        "expression": BUILTIN_FUNCTIONS | {"id"},
        "atom": BUILTIN_FUNCTIONS,
        "value": BUILTIN_FUNCTIONS,
        "condition": BUILTIN_FUNCTIONS,
        "bool_ctrl": BUILTIN_FUNCTIONS,
    }
    for nonterminal, required_symbols in required_first_memberships.items():
        missing = required_symbols - FIRST.get(nonterminal, frozenset())
        if missing:
            raise RuntimeError(
                f"FIRST({nonterminal}) is missing revised built-in terminals: {sorted(missing)}"
            )

    required_predict = {
        91: BUILTIN_FUNCTIONS,
        136: BUILTIN_FUNCTIONS,
        152: {"abs"},
        153: {"len"},
        154: {"pow"},
        155: {"sqrt"},
        190: BUILTIN_FUNCTIONS,
    }
    for production_no, required_symbols in required_predict.items():
        missing = required_symbols - PREDICT.get(production_no, frozenset())
        if missing:
            raise RuntimeError(
                f"PREDICT[{production_no}] is missing revised built-in terminals: {sorted(missing)}"
            )


_validate_tables()
