"""
PORTIA Language Grammar Definition
===================================

This module exports token-class constants plus the revised CFG, FIRST,
FOLLOW, and PREDICT tables consumed by the recursive-descent parser.

247 productions / 116 non-terminals
"""

from __future__ import annotations

from typing import Dict, FrozenSet, Iterable, Tuple


# =========================================================================
# Token-class constants
# =========================================================================
DTYPE_KEYWORDS = frozenset({"int", "long", "float", "double", "char", "string", "bool"})
LITERAL_TYPES = frozenset({"INTLIT", "LONGLIT", "FLOATLIT", "DOUBLELIT", "CHARLIT", "STRINGLIT"})
NUM_LIT_TYPES = frozenset({"INTLIT", "LONGLIT", "FLOATLIT", "DOUBLELIT"})
WHOLE_LIT_TYPES = frozenset({"INTLIT", "LONGLIT"})
REL_OPS = frozenset({"==", "!=", ">", "<", ">=", "<="})
ASSIGN_OPS = frozenset({"=", "+=", "-=", "*=", "/=", "%="})
UPDATE_OPS = frozenset({"+=", "-=", "*=", "/=", "%="})
BOOL_LITERALS = frozenset({"true", "false"})
ADDITIVE_OPS = frozenset({"+", "-"})
MULT_OPS = frozenset({"*", "/", "%"})
BUILTIN_FUNCTIONS = frozenset({"abs", "len", "pow", "sqrt"})
BUILTIN_FIXED_ARITY = {"abs": 1, "len": 1, "pow": 2, "sqrt": 1}

GRAMMAR_RULE_COUNT = 247
NON_TERMINAL_COUNT = 116


# =========================================================================
# Direct grammar table helpers
# =========================================================================
def _prod(lhs: str, *rhs: str) -> Tuple[str, Tuple[str, ...]]:
    return lhs, rhs


def _freeze_named_table(table: Dict[str, Iterable[str]]) -> Dict[str, FrozenSet[str]]:
    return {key: frozenset(values) for key, values in table.items()}


def _freeze_predict_table(table: Dict[int, Iterable[str]]) -> Dict[int, FrozenSet[str]]:
    return {key: frozenset(values) for key, values in table.items()}


# =========================================================================
# CFG productions
# =========================================================================
CFG = {
    1: _prod("program", "global_dec", "function", "main_func"),
    2: _prod("global_dec", "global", "mutability", ";", "global_dec"),
    3: _prod("global_dec", "weave_def", "global_dec"),
    4: _prod("global_dec"),
    5: _prod("mutability", "var", "var_or_weave"),
    6: _prod("mutability", "const", "const_weave"),
    7: _prod("var_or_weave", "dtype", "id", "var_or_arr"),
    8: _prod("var_or_weave", "id", "id", "=", "{", "weave_init_list", "}"),
    9: _prod("const_weave", "dtype", "id", "const_or_arr"),
    10: _prod("const_weave", "id", "id", "=", "{", "weave_init_list", "}"),
    11: _prod("dtype", "int"),
    12: _prod("dtype", "long"),
    13: _prod("dtype", "float"),
    14: _prod("dtype", "double"),
    15: _prod("dtype", "char"),
    16: _prod("dtype", "string"),
    17: _prod("dtype", "bool"),
    18: _prod("var_or_arr", "=", "value", "multi_dec"),
    19: _prod("var_or_arr", "[", "size", "]", "var_1D_or_2D"),
    20: _prod("const_or_arr", "=", "literals_num", "multi_dec"),
    21: _prod("const_or_arr", "[", "size", "]", "const_1D_or_2D"),
    22: _prod("value", "string_or_logical_expr"),
    23: _prod("multi_dec", ",", "id", "=", "value", "multi_dec"),
    24: _prod("multi_dec"),
    25: _prod("size", "intlit"),
    26: _prod("literals_num", "literals"),
    27: _prod("literals_num", "-", "num_lit"),
    28: _prod("num_lit", "intlit"),
    29: _prod("num_lit", "longlit"),
    30: _prod("num_lit", "floatlit"),
    31: _prod("num_lit", "doublelit"),
    32: _prod("var_1D_or_2D", "=", "{", "1D_elem_list", "}"),
    33: _prod("var_1D_or_2D", "[", "size", "]", "arr_2D_init_opt"),
    34: _prod("var_1D_or_2D"),
    35: _prod("1D_elem_list", "elem_value", "1D_elem_list_tail"),
    36: _prod("elem_value", "literals"),
    37: _prod("elem_value", "id"),
    38: _prod("1D_elem_list_tail", ",", "elem_value", "1D_elem_list_tail"),
    39: _prod("1D_elem_list_tail"),
    40: _prod("arr_2D_init_opt", "arr_2D_init"),
    41: _prod("arr_2D_init_opt"),
    42: _prod("arr_2D_init", "=", "{", "2D_elem_list", "}"),
    43: _prod("2D_elem_list", "{", "1D_elem_list", "}", "2D_elem_list_cont"),
    44: _prod("2D_elem_list_cont", ",", "2D_elem_list"),
    45: _prod("2D_elem_list_cont"),
    46: _prod("const_1D_or_2D", "=", "{", "1D_elem_list", "}"),
    47: _prod("const_1D_or_2D", "[", "size", "]", "arr_2D_init"),
    48: _prod("weave_init_list", "weave_elem", "weave_init_list_tail"),
    49: _prod("weave_elem", "literals_num"),
    50: _prod("weave_elem", "id"),
    51: _prod("weave_init_list_tail", ",", "weave_elem", "weave_init_list_tail"),
    52: _prod("weave_init_list_tail"),
    53: _prod("weave_def", "weave", "id", "{", "field_list", "}"),
    54: _prod("field_list", "field_dec", "field_list"),
    55: _prod("field_list"),
    56: _prod("field_dec", "dtype", "id", ";"),
    57: _prod("function", "function_def", "function"),
    58: _prod("function"),
    59: _prod("function_def", "func", "ret_type"),
    60: _prod("ret_type", "dtype", "ret_struct", "id", "(", "param", ")", "{", "function_body", "ret_stmt", "}"),
    61: _prod("ret_type", "void", "id", "(", ")", "{", "function_body", "return", ";", "}"),
    62: _prod("ret_struct", "[", "size", "]", "ret_2D"),
    63: _prod("ret_struct"),
    64: _prod("ret_2D", "[", "size", "]"),
    65: _prod("ret_2D"),
    66: _prod("param", "dtype", "id", "param_struct", "param_tail"),
    67: _prod("param"),
    68: _prod("param_tail", ",", "param"),
    69: _prod("param_tail"),
    70: _prod("param_struct", "[", "size", "]", "param_2D"),
    71: _prod("param_struct"),
    72: _prod("param_2D", "[", "size", "]"),
    73: _prod("param_2D"),
    74: _prod("function_body", "using_block", "local_block", "statement_list"),
    75: _prod("using_block", "using_stmt", ";", "using_block"),
    76: _prod("using_block"),
    77: _prod("using_stmt", "using", "id", "using_cont"),
    78: _prod("using_cont", ",", "id", "using_cont"),
    79: _prod("using_cont"),
    80: _prod("local_block", "local", "mutability", ";", "local_block"),
    81: _prod("local_block"),
    82: _prod("statement_list", "statement", "statement_list"),
    83: _prod("statement_list"),
    84: _prod("statement", "expression", ";"),
    85: _prod("statement", "I/O_stmt"),
    86: _prod("statement", "ctrl_struct"),
    87: _prod("expression", "assign_expr"),
    88: _prod("expression", "builtin_func"),
    89: _prod("assign_expr", "id", "mod_or_call"),
    90: _prod("mod_or_call", "assign_mod_opt", "assign_stmt_op"),
    91: _prod("mod_or_call", "(", "arg", ")"),
    92: _prod("assign_mod_opt", ".", "id"),
    93: _prod("assign_mod_opt", "[", "size_mod", "]", "lhs_index_2d_opt"),
    94: _prod("assign_mod_opt"),
    95: _prod("lhs_index_2d_opt", "[", "size_mod", "]"),
    96: _prod("lhs_index_2d_opt"),
    97: _prod("assign_stmt_op", "=", "value"),
    98: _prod("assign_stmt_op", "+=", "value"),
    99: _prod("assign_stmt_op", "-=", "value"),
    100: _prod("assign_stmt_op", "*=", "value"),
    101: _prod("assign_stmt_op", "/=", "value"),
    102: _prod("assign_stmt_op", "%=", "value"),
    103: _prod("size_mod", "intlit"),
    104: _prod("size_mod", "id"),
    105: _prod("string_or_logical_expr", "logical_expr", "string_expr_tail"),
    106: _prod("string_expr_tail", "..", "logical_expr", "string_expr_tail"),
    107: _prod("string_expr_tail"),
    108: _prod("logical_expr", "logical_term", "logical_expr_tail"),
    109: _prod("logical_expr_tail", "||", "logical_term", "logical_expr_tail"),
    110: _prod("logical_expr_tail"),
    111: _prod("logical_term", "logical_factor", "logical_term_tail"),
    112: _prod("logical_term_tail", "&&", "logical_factor", "logical_term_tail"),
    113: _prod("logical_term_tail"),
    114: _prod("logical_factor", "!", "logical_factor"),
    115: _prod("logical_factor", "rel_expr"),
    116: _prod("rel_expr", "arith_expr", "rel_op", "arith_expr"),
    117: _prod("arith_expr", "term", "add_min_cont"),
    118: _prod("add_min_cont", "+", "term", "add_min_cont"),
    119: _prod("add_min_cont", "-", "term", "add_min_cont"),
    120: _prod("add_min_cont"),
    121: _prod("term", "primary", "mult_div_modulo_cont"),
    122: _prod("mult_div_modulo_cont", "*", "primary", "mult_div_modulo_cont"),
    123: _prod("mult_div_modulo_cont", "/", "primary", "mult_div_modulo_cont"),
    124: _prod("mult_div_modulo_cont", "%", "primary", "mult_div_modulo_cont"),
    125: _prod("mult_div_modulo_cont"),
    126: _prod("primary", "atom"),
    127: _prod("primary", "-", "primary"),
    128: _prod("primary", "(", "cast_or_val"),
    129: _prod("cast_or_val", "dtype", ")", "primary"),
    130: _prod("cast_or_val", "value", ")"),
    131: _prod("atom", "id", "iden_mod"),
    132: _prod("atom", "literals"),
    133: _prod("atom", "builtin_func"),
    134: _prod("iden_mod", "arr_or_func"),
    135: _prod("iden_mod", ".", "id"),
    136: _prod("arr_or_func", "[", "size", "]", "2D_array"),
    137: _prod("arr_or_func", "(", "arg", ")"),
    138: _prod("arr_or_func"),
    139: _prod("2D_array", "[", "size", "]"),
    140: _prod("2D_array"),
    141: _prod("literals", "intlit"),
    142: _prod("literals", "longlit"),
    143: _prod("literals", "floatlit"),
    144: _prod("literals", "doublelit"),
    145: _prod("literals", "charlit"),
    146: _prod("literals", "stringlit"),
    147: _prod("literals", "true"),
    148: _prod("literals", "false"),
    149: _prod("builtin_func", "abs", "(", "value", ")"),
    150: _prod("builtin_func", "len", "(", "value", ")"),
    151: _prod("builtin_func", "pow", "(", "value", ",", "value", ")"),
    152: _prod("builtin_func", "sqrt", "(", "value", ")"),
    153: _prod("arg", "value", "multi_arg"),
    154: _prod("arg"),
    155: _prod("multi_arg", ",", "arg"),
    156: _prod("multi_arg"),
    157: _prod("I/O_stmt", "input_stmt"),
    158: _prod("I/O_stmt", "output_stmt"),
    159: _prod("input_stmt", "trap", "(", "trap_target", ")", ";"),
    160: _prod("trap_target", "id", "trap_suffix"),
    161: _prod("trap_suffix", "[", "size", "]", "2D_array"),
    162: _prod("trap_suffix", ".", "id"),
    163: _prod("trap_suffix"),
    164: _prod("output_stmt", "thread", "(", "print_args", ")", ";"),
    165: _prod("output_stmt", "threadln", "(", "print_args", ")", ";"),
    166: _prod("print_args", "value", "print_tail"),
    167: _prod("print_tail", ",", "value", "print_tail"),
    168: _prod("print_tail"),
    169: _prod("ctrl_struct", "conditional_stmt"),
    170: _prod("ctrl_struct", "loop_stmt"),
    171: _prod("conditional_stmt", "if_stmt"),
    172: _prod("conditional_stmt", "switch_stmt"),
    173: _prod("if_stmt", "if", "(", "condition", ")", "{", "ctrl_body", "ret_ctrl_body", "}", "else_if_ei_stmt"),
    174: _prod("condition", "and_expr", "or_tail"),
    175: _prod("or_tail", "||", "and_expr", "or_tail"),
    176: _prod("or_tail"),
    177: _prod("and_expr", "logical_op", "and_tail"),
    178: _prod("and_tail", "&&", "logical_op", "and_tail"),
    179: _prod("and_tail"),
    180: _prod("logical_op", "!", "logical_op"),
    181: _prod("logical_op", "bool_ctrl"),
    182: _prod("bool_ctrl", "id", "iden_mod", "mult_div_modulo_cont", "add_min_cont", "bool_ctrl_tail"),
    183: _prod("bool_ctrl", "true", "mult_div_modulo_cont", "add_min_cont", "bool_ctrl_tail"),
    184: _prod("bool_ctrl", "false", "mult_div_modulo_cont", "add_min_cont", "bool_ctrl_tail"),
    185: _prod("bool_ctrl", "(", "cast_or_val", "mult_div_modulo_cont", "add_min_cont", "bool_ctrl_tail"),
    186: _prod("bool_ctrl", "cmp_start", "mult_div_modulo_cont", "add_min_cont", "rel_op", "arith_expr"),
    187: _prod("bool_ctrl", "builtin_func", "mult_div_modulo_cont", "add_min_cont", "bool_ctrl_tail"),
    188: _prod("bool_ctrl_tail", "rel_op", "arith_expr"),
    189: _prod("bool_ctrl_tail"),
    190: _prod("cmp_start", "-", "primary"),
    191: _prod("cmp_start", "intlit"),
    192: _prod("cmp_start", "longlit"),
    193: _prod("cmp_start", "floatlit"),
    194: _prod("cmp_start", "doublelit"),
    195: _prod("cmp_start", "charlit"),
    196: _prod("cmp_start", "stringlit"),
    197: _prod("rel_op", "=="),
    198: _prod("rel_op", "!="),
    199: _prod("rel_op", ">"),
    200: _prod("rel_op", "<"),
    201: _prod("rel_op", ">="),
    202: _prod("rel_op", "<="),
    203: _prod("ctrl_body", "local_block", "ctrl_statement_list"),
    204: _prod("ctrl_statement_list", "statement_list", "break_opt"),
    205: _prod("break_opt", "break", ";"),
    206: _prod("break_opt"),
    207: _prod("ret_ctrl_body", "ret_stmt"),
    208: _prod("ret_ctrl_body"),
    209: _prod("else_if_ei_stmt", "else", "else_stmt"),
    210: _prod("else_if_ei_stmt"),
    211: _prod("else_stmt", "if_stmt"),
    212: _prod("else_stmt", "{", "ctrl_body", "ret_ctrl_body", "}"),
    213: _prod("switch_stmt", "switch", "(", "switch_val", ")", "{", "case_list", "default_stmt", "}"),
    214: _prod("case_list", "case_stmt", "case_list"),
    215: _prod("case_list"),
    216: _prod("switch_val", "logical_expr"),
    217: _prod("case_stmt", "case", "case_val", ":", "ctrl_body", "ret_ctrl_body"),
    218: _prod("case_val", "unique_val"),
    219: _prod("unique_val", "charlit"),
    220: _prod("unique_val", "true"),
    221: _prod("unique_val", "false"),
    222: _prod("unique_val", "intlit"),
    223: _prod("unique_val", "longlit"),
    224: _prod("unique_val", "-", "whole_lit"),
    225: _prod("whole_lit", "intlit"),
    226: _prod("whole_lit", "longlit"),
    227: _prod("default_stmt", "default", ":", "ctrl_body", "ret_ctrl_body"),
    228: _prod("default_stmt"),
    229: _prod("loop_stmt", "for_stmt"),
    230: _prod("loop_stmt", "while_stmt"),
    231: _prod("loop_stmt", "do_stmt"),
    232: _prod("for_stmt", "for", "(", "initializer", ";", "condition", ";", "update", ")", "{", "ctrl_body", "ret_ctrl_body", "}"),
    233: _prod("initializer", "local", "var", "dtype", "id", "=", "literals_num"),
    234: _prod("initializer", "id", "=", "literals_num"),
    235: _prod("initializer"),
    236: _prod("update", "id", "update_op", "arith_expr"),
    237: _prod("update"),
    238: _prod("update_op", "+="),
    239: _prod("update_op", "-="),
    240: _prod("update_op", "*="),
    241: _prod("update_op", "/="),
    242: _prod("update_op", "%="),
    243: _prod("while_stmt", "while", "(", "condition", ")", "{", "ctrl_body", "ret_ctrl_body", "}"),
    244: _prod("do_stmt", "do", "{", "ctrl_body", "ret_ctrl_body", "}", "while", "(", "condition", ")", ";"),
    245: _prod("ret_stmt", "return", "value", ";"),
    246: _prod("main_func", "int", "main", "(", ")", "{", "main_body", "}"),
    247: _prod("main_body", "using_block", "local_block", "statement_list", "return", "intlit", ";"),
}


# =========================================================================
# FIRST sets (nullable productions use FOLLOW in the parser)
# =========================================================================
FIRST = _freeze_named_table({
    "program": {"func", "global", "int", "weave"},
    "global_dec": {"global", "weave"},
    "mutability": {"const", "var"},
    "var_or_weave": {"bool", "char", "double", "float", "id", "int", "long", "string"},
    "const_weave": {"bool", "char", "double", "float", "id", "int", "long", "string"},
    "dtype": {"bool", "char", "double", "float", "int", "long", "string"},
    "var_or_arr": {"=", "["},
    "const_or_arr": {"=", "["},
    "value": {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "multi_dec": {","},
    "size": {"intlit"},
    "literals_num": {"-", "charlit", "doublelit", "false", "floatlit", "intlit", "longlit", "stringlit", "true"},
    "num_lit": {"doublelit", "floatlit", "intlit", "longlit"},
    "var_1D_or_2D": {"=", "["},
    "1D_elem_list": {"charlit", "doublelit", "false", "floatlit", "id", "intlit", "longlit", "stringlit", "true"},
    "elem_value": {"charlit", "doublelit", "false", "floatlit", "id", "intlit", "longlit", "stringlit", "true"},
    "1D_elem_list_tail": {","},
    "arr_2D_init_opt": {"="},
    "arr_2D_init": {"="},
    "2D_elem_list": {"{"},
    "2D_elem_list_cont": {","},
    "const_1D_or_2D": {"=", "["},
    "weave_init_list": {"-", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "longlit", "stringlit", "true"},
    "weave_elem": {"-", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "longlit", "stringlit", "true"},
    "weave_init_list_tail": {","},
    "weave_def": {"weave"},
    "field_list": {"bool", "char", "double", "float", "int", "long", "string"},
    "field_dec": {"bool", "char", "double", "float", "int", "long", "string"},
    "function": {"func"},
    "function_def": {"func"},
    "ret_type": {"bool", "char", "double", "float", "int", "long", "string", "void"},
    "ret_struct": {"["},
    "ret_2D": {"["},
    "param": {"bool", "char", "double", "float", "int", "long", "string"},
    "param_tail": {","},
    "param_struct": {"["},
    "param_2D": {"["},
    "function_body": {"abs", "do", "for", "id", "if", "len", "local", "pow", "sqrt", "switch", "thread", "threadln", "trap", "using", "while"},
    "using_block": {"using"},
    "using_stmt": {"using"},
    "using_cont": {","},
    "local_block": {"local"},
    "statement_list": {"abs", "do", "for", "id", "if", "len", "pow", "sqrt", "switch", "thread", "threadln", "trap", "while"},
    "statement": {"abs", "do", "for", "id", "if", "len", "pow", "sqrt", "switch", "thread", "threadln", "trap", "while"},
    "expression": {"abs", "id", "len", "pow", "sqrt"},
    "assign_expr": {"id"},
    "mod_or_call": {"%=", "(", "*=", "+=", "-=", ".", "/=", "=", "["},
    "assign_mod_opt": {".", "["},
    "lhs_index_2d_opt": {"["},
    "assign_stmt_op": {"%=", "*=", "+=", "-=", "/=", "="},
    "size_mod": {"id", "intlit"},
    "string_or_logical_expr": {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "string_expr_tail": {".."},
    "logical_expr": {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "logical_expr_tail": {"||"},
    "logical_term": {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "logical_term_tail": {"&&"},
    "logical_factor": {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "rel_expr": {"(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "arith_expr": {"(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "add_min_cont": {"+", "-"},
    "term": {"(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "mult_div_modulo_cont": {"%", "*", "/"},
    "primary": {"(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "cast_or_val": {"!", "(", "-", "abs", "bool", "char", "charlit", "double", "doublelit", "false", "float", "floatlit", "id", "int", "intlit", "len", "long", "longlit", "pow", "sqrt", "string", "stringlit", "true"},
    "atom": {"abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "iden_mod": {"(", ".", "["},
    "arr_or_func": {"(", "["},
    "2D_array": {"["},
    "literals": {"charlit", "doublelit", "false", "floatlit", "intlit", "longlit", "stringlit", "true"},
    "builtin_func": {"abs", "len", "pow", "sqrt"},
    "arg": {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "multi_arg": {","},
    "I/O_stmt": {"thread", "threadln", "trap"},
    "input_stmt": {"trap"},
    "trap_target": {"id"},
    "trap_suffix": {".", "["},
    "output_stmt": {"thread", "threadln"},
    "print_args": {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "print_tail": {","},
    "ctrl_struct": {"do", "for", "if", "switch", "while"},
    "conditional_stmt": {"if", "switch"},
    "if_stmt": {"if"},
    "condition": {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "or_tail": {"||"},
    "and_expr": {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "and_tail": {"&&"},
    "logical_op": {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "bool_ctrl": {"(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "bool_ctrl_tail": {"!=", "<", "<=", "==", ">", ">="},
    "cmp_start": {"-", "charlit", "doublelit", "floatlit", "intlit", "longlit", "stringlit"},
    "rel_op": {"!=", "<", "<=", "==", ">", ">="},
    "ctrl_body": {"abs", "break", "do", "for", "id", "if", "len", "local", "pow", "sqrt", "switch", "thread", "threadln", "trap", "while"},
    "ctrl_statement_list": {"abs", "break", "do", "for", "id", "if", "len", "pow", "sqrt", "switch", "thread", "threadln", "trap", "while"},
    "break_opt": {"break"},
    "ret_ctrl_body": {"return"},
    "else_if_ei_stmt": {"else"},
    "else_stmt": {"if", "{"},
    "switch_stmt": {"switch"},
    "case_list": {"case"},
    "switch_val": {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "case_stmt": {"case"},
    "case_val": {"-", "charlit", "false", "intlit", "longlit", "true"},
    "unique_val": {"-", "charlit", "false", "intlit", "longlit", "true"},
    "whole_lit": {"intlit", "longlit"},
    "default_stmt": {"default"},
    "loop_stmt": {"do", "for", "while"},
    "for_stmt": {"for"},
    "initializer": {"id", "local"},
    "update": {"id"},
    "update_op": {"%=", "*=", "+=", "-=", "/="},
    "while_stmt": {"while"},
    "do_stmt": {"do"},
    "ret_stmt": {"return"},
    "main_func": {"int"},
    "main_body": {"abs", "do", "for", "id", "if", "len", "local", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "using", "while"},
})


# =========================================================================
# FOLLOW sets
# =========================================================================
FOLLOW = _freeze_named_table({
    "program": set(),
    "global_dec": {"func", "int"},
    "mutability": {";"},
    "var_or_weave": {";"},
    "const_weave": {";"},
    "dtype": {")", "[", "id"},
    "var_or_arr": {";"},
    "const_or_arr": {";"},
    "value": {")", ",", ";"},
    "multi_dec": {";"},
    "size": {"]"},
    "literals_num": {",", ";", "}"},
    "num_lit": {",", ";", "}"},
    "var_1D_or_2D": {";"},
    "1D_elem_list": {"}"},
    "elem_value": {",", "}"},
    "1D_elem_list_tail": {"}"},
    "arr_2D_init_opt": {";"},
    "arr_2D_init": {";"},
    "2D_elem_list": {"}"},
    "2D_elem_list_cont": {"}"},
    "const_1D_or_2D": {";"},
    "weave_init_list": {"}"},
    "weave_elem": {",", "}"},
    "weave_init_list_tail": {"}"},
    "weave_def": {"func", "global", "int", "weave"},
    "field_list": {"}"},
    "field_dec": {"bool", "char", "double", "float", "int", "long", "string", "}"},
    "function": {"int"},
    "function_def": {"func", "int"},
    "ret_type": {"func", "int"},
    "ret_struct": {"id"},
    "ret_2D": {"id"},
    "param": {")"},
    "param_tail": {")"},
    "param_struct": {")", ","},
    "param_2D": {")", ","},
    "function_body": {"return"},
    "using_block": {"abs", "do", "for", "id", "if", "len", "local", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while"},
    "using_stmt": {";"},
    "using_cont": {";"},
    "local_block": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "statement_list": {"break", "case", "default", "return", "}"},
    "statement": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "expression": {";"},
    "assign_expr": {";"},
    "mod_or_call": {";"},
    "assign_mod_opt": {"%=", "*=", "+=", "-=", "/=", "="},
    "lhs_index_2d_opt": {"%=", "*=", "+=", "-=", "/=", "="},
    "assign_stmt_op": {";"},
    "size_mod": {"]"},
    "string_or_logical_expr": {")", ",", ";"},
    "string_expr_tail": {")", ",", ";"},
    "logical_expr": {")", ",", "..", ";"},
    "logical_expr_tail": {")", ",", "..", ";"},
    "logical_term": {")", ",", "..", ";", "||"},
    "logical_term_tail": {")", ",", "..", ";", "||"},
    "logical_factor": {"&&", ")", ",", "..", ";", "||"},
    "rel_expr": {"&&", ")", ",", "..", ";", "||"},
    "arith_expr": {"!=", "&&", ")", ",", "..", ";", "<", "<=", "==", ">", ">=", "||"},
    "add_min_cont": {"!=", "&&", ")", ",", "..", ";", "<", "<=", "==", ">", ">=", "||"},
    "term": {"!=", "&&", ")", "+", ",", "-", "..", ";", "<", "<=", "==", ">", ">=", "||"},
    "mult_div_modulo_cont": {"!=", "&&", ")", "+", ",", "-", "..", ";", "<", "<=", "==", ">", ">=", "||"},
    "primary": {"!=", "%", "&&", ")", "*", "+", ",", "-", "..", "/", ";", "<", "<=", "==", ">", ">=", "||"},
    "cast_or_val": {"!=", "%", "&&", ")", "*", "+", ",", "-", "..", "/", ";", "<", "<=", "==", ">", ">=", "||"},
    "atom": {"!=", "%", "&&", ")", "*", "+", ",", "-", "..", "/", ";", "<", "<=", "==", ">", ">=", "||"},
    "iden_mod": {"!=", "%", "&&", ")", "*", "+", ",", "-", "..", "/", ";", "<", "<=", "==", ">", ">=", "||"},
    "arr_or_func": {"!=", "%", "&&", ")", "*", "+", ",", "-", "..", "/", ";", "<", "<=", "==", ">", ">=", "||"},
    "2D_array": {"!=", "%", "&&", ")", "*", "+", ",", "-", "..", "/", ";", "<", "<=", "==", ">", ">=", "||"},
    "literals": {"!=", "%", "&&", ")", "*", "+", ",", "-", "..", "/", ";", "<", "<=", "==", ">", ">=", "||", "}"},
    "builtin_func": {"!=", "%", "&&", ")", "*", "+", ",", "-", "..", "/", ";", "<", "<=", "==", ">", ">=", "||"},
    "arg": {")"},
    "multi_arg": {")"},
    "I/O_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "input_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "trap_target": {")"},
    "trap_suffix": {")"},
    "output_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "print_args": {")"},
    "print_tail": {")"},
    "ctrl_struct": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "conditional_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "if_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "condition": {")", ";"},
    "or_tail": {")", ";"},
    "and_expr": {")", ";", "||"},
    "and_tail": {")", ";", "||"},
    "logical_op": {"&&", ")", ";", "||"},
    "bool_ctrl": set(),
    "bool_ctrl_tail": set(),
    "cmp_start": {"!=", "%", "*", "+", "-", "/", "<", "<=", "==", ">", ">="},
    "rel_op": {"(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "ctrl_body": {"case", "default", "return", "}"},
    "ctrl_statement_list": {"case", "default", "return", "}"},
    "break_opt": {"case", "default", "return", "}"},
    "ret_ctrl_body": {"case", "default", "}"},
    "else_if_ei_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "else_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "switch_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "case_list": {"default", "}"},
    "switch_val": {")"},
    "case_stmt": {"case", "default", "}"},
    "case_val": {":"},
    "unique_val": {":"},
    "whole_lit": {":"},
    "default_stmt": {"}"},
    "loop_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "for_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "initializer": {";"},
    "update": {")"},
    "update_op": {"(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    "while_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "do_stmt": {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    "ret_stmt": {"case", "default", "}"},
    "main_func": set(),
    "main_body": {"}"},
})


# =========================================================================
# PREDICT sets keyed by production number
# =========================================================================
PREDICT = _freeze_predict_table({
    1: {"func", "global", "int", "weave"},
    2: {"global"},
    3: {"weave"},
    4: {"func", "int"},
    5: {"var"},
    6: {"const"},
    7: {"bool", "char", "double", "float", "int", "long", "string"},
    8: {"id"},
    9: {"bool", "char", "double", "float", "int", "long", "string"},
    10: {"id"},
    11: {"int"},
    12: {"long"},
    13: {"float"},
    14: {"double"},
    15: {"char"},
    16: {"string"},
    17: {"bool"},
    18: {"="},
    19: {"["},
    20: {"="},
    21: {"["},
    22: {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    23: {","},
    24: {";"},
    25: {"intlit"},
    26: {"charlit", "doublelit", "false", "floatlit", "intlit", "longlit", "stringlit", "true"},
    27: {"-"},
    28: {"intlit"},
    29: {"longlit"},
    30: {"floatlit"},
    31: {"doublelit"},
    32: {"="},
    33: {"["},
    34: {";"},
    35: {"charlit", "doublelit", "false", "floatlit", "id", "intlit", "longlit", "stringlit", "true"},
    36: {"charlit", "doublelit", "false", "floatlit", "intlit", "longlit", "stringlit", "true"},
    37: {"id"},
    38: {","},
    39: {"}"},
    40: {"="},
    41: {";"},
    42: {"="},
    43: {"{"},
    44: {","},
    45: {"}"},
    46: {"="},
    47: {"["},
    48: {"-", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "longlit", "stringlit", "true"},
    49: {"-", "charlit", "doublelit", "false", "floatlit", "intlit", "longlit", "stringlit", "true"},
    50: {"id"},
    51: {","},
    52: {"}"},
    53: {"weave"},
    54: {"bool", "char", "double", "float", "int", "long", "string"},
    55: {"}"},
    56: {"bool", "char", "double", "float", "int", "long", "string"},
    57: {"func"},
    58: {"int"},
    59: {"func"},
    60: {"bool", "char", "double", "float", "int", "long", "string"},
    61: {"void"},
    62: {"["},
    63: {"id"},
    64: {"["},
    65: {"id"},
    66: {"bool", "char", "double", "float", "int", "long", "string"},
    67: {")"},
    68: {","},
    69: {")"},
    70: {"["},
    71: {")", ","},
    72: {"["},
    73: {")", ","},
    74: {"abs", "do", "for", "id", "if", "len", "local", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "using", "while"},
    75: {"using"},
    76: {"abs", "do", "for", "id", "if", "len", "local", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while"},
    77: {"using"},
    78: {","},
    79: {";"},
    80: {"local"},
    81: {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    82: {"abs", "do", "for", "id", "if", "len", "pow", "sqrt", "switch", "thread", "threadln", "trap", "while"},
    83: {"break", "case", "default", "return", "}"},
    84: {"abs", "id", "len", "pow", "sqrt"},
    85: {"thread", "threadln", "trap"},
    86: {"do", "for", "if", "switch", "while"},
    87: {"id"},
    88: {"abs", "len", "pow", "sqrt"},
    89: {"id"},
    90: {"%=", "*=", "+=", "-=", ".", "/=", "=", "["},
    91: {"("},
    92: {"."},
    93: {"["},
    94: {"%=", "*=", "+=", "-=", "/=", "="},
    95: {"["},
    96: {"%=", "*=", "+=", "-=", "/=", "="},
    97: {"="},
    98: {"+="},
    99: {"-="},
    100: {"*="},
    101: {"/="},
    102: {"%="},
    103: {"intlit"},
    104: {"id"},
    105: {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    106: {".."},
    107: {")", ",", ";"},
    108: {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    109: {"||"},
    110: {")", ",", "..", ";"},
    111: {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    112: {"&&"},
    113: {")", ",", "..", ";", "||"},
    114: {"!"},
    115: {"(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    116: {"(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    117: {"(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    118: {"+"},
    119: {"-"},
    120: {"!=", "&&", ")", ",", "..", ";", "<", "<=", "==", ">", ">=", "||"},
    121: {"(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    122: {"*"},
    123: {"/"},
    124: {"%"},
    125: {"!=", "&&", ")", "+", ",", "-", "..", ";", "<", "<=", "==", ">", ">=", "||"},
    126: {"abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    127: {"-"},
    128: {"("},
    129: {"bool", "char", "double", "float", "int", "long", "string"},
    130: {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    131: {"id"},
    132: {"charlit", "doublelit", "false", "floatlit", "intlit", "longlit", "stringlit", "true"},
    133: {"abs", "len", "pow", "sqrt"},
    134: {"!=", "%", "&&", "(", ")", "*", "+", ",", "-", "..", "/", ";", "<", "<=", "==", ">", ">=", "[", "||"},
    135: {"."},
    136: {"["},
    137: {"("},
    138: {"!=", "%", "&&", ")", "*", "+", ",", "-", "..", "/", ";", "<", "<=", "==", ">", ">=", "||"},
    139: {"["},
    140: {"!=", "%", "&&", ")", "*", "+", ",", "-", "..", "/", ";", "<", "<=", "==", ">", ">=", "||"},
    141: {"intlit"},
    142: {"longlit"},
    143: {"floatlit"},
    144: {"doublelit"},
    145: {"charlit"},
    146: {"stringlit"},
    147: {"true"},
    148: {"false"},
    149: {"abs"},
    150: {"len"},
    151: {"pow"},
    152: {"sqrt"},
    153: {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    154: {")"},
    155: {","},
    156: {")"},
    157: {"trap"},
    158: {"thread", "threadln"},
    159: {"trap"},
    160: {"id"},
    161: {"["},
    162: {"."},
    163: {")"},
    164: {"thread"},
    165: {"threadln"},
    166: {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    167: {","},
    168: {")"},
    169: {"if", "switch"},
    170: {"do", "for", "while"},
    171: {"if"},
    172: {"switch"},
    173: {"if"},
    174: {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    175: {"||"},
    176: {")", ";"},
    177: {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    178: {"&&"},
    179: {")", ";", "||"},
    180: {"!"},
    181: {"(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    182: {"id"},
    183: {"true"},
    184: {"false"},
    185: {"("},
    186: {"-", "charlit", "doublelit", "floatlit", "intlit", "longlit", "stringlit"},
    187: {"abs", "len", "pow", "sqrt"},
    188: {"!=", "<", "<=", "==", ">", ">="},
    189: set(),
    190: {"-"},
    191: {"intlit"},
    192: {"longlit"},
    193: {"floatlit"},
    194: {"doublelit"},
    195: {"charlit"},
    196: {"stringlit"},
    197: {"=="},
    198: {"!="},
    199: {">"},
    200: {"<"},
    201: {">="},
    202: {"<="},
    203: {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "local", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    204: {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    205: {"break"},
    206: {"case", "default", "return", "}"},
    207: {"return"},
    208: {"case", "default", "}"},
    209: {"else"},
    210: {"abs", "break", "case", "default", "do", "for", "id", "if", "len", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "while", "}"},
    211: {"if"},
    212: {"{"},
    213: {"switch"},
    214: {"case"},
    215: {"default", "}"},
    216: {"!", "(", "-", "abs", "charlit", "doublelit", "false", "floatlit", "id", "intlit", "len", "longlit", "pow", "sqrt", "stringlit", "true"},
    217: {"case"},
    218: {"-", "charlit", "false", "intlit", "longlit", "true"},
    219: {"charlit"},
    220: {"true"},
    221: {"false"},
    222: {"intlit"},
    223: {"longlit"},
    224: {"-"},
    225: {"intlit"},
    226: {"longlit"},
    227: {"default"},
    228: {"}"},
    229: {"for"},
    230: {"while"},
    231: {"do"},
    232: {"for"},
    233: {"local"},
    234: {"id"},
    235: {";"},
    236: {"id"},
    237: {")"},
    238: {"+="},
    239: {"-="},
    240: {"*="},
    241: {"/="},
    242: {"%="},
    243: {"while"},
    244: {"do"},
    245: {"return"},
    246: {"int"},
    247: {"abs", "do", "for", "id", "if", "len", "local", "pow", "return", "sqrt", "switch", "thread", "threadln", "trap", "using", "while"},
})


def _validate_tables() -> None:
    if len(CFG) != GRAMMAR_RULE_COUNT:
        raise RuntimeError(
            f"Expected {GRAMMAR_RULE_COUNT} CFG productions, found {len(CFG)}"
        )
    if len(FIRST) != NON_TERMINAL_COUNT:
        raise RuntimeError(
            f"Expected {NON_TERMINAL_COUNT} FIRST-set entries, found {len(FIRST)}"
        )
    if len(FOLLOW) != NON_TERMINAL_COUNT:
        raise RuntimeError(
            f"Expected {NON_TERMINAL_COUNT} FOLLOW-set entries, found {len(FOLLOW)}"
        )
    if set(FIRST) != set(FOLLOW):
        raise RuntimeError("FIRST and FOLLOW tables do not cover the same non-terminals")
    if len(PREDICT) != GRAMMAR_RULE_COUNT:
        raise RuntimeError(
            f"Expected {GRAMMAR_RULE_COUNT} PREDICT-set entries, found {len(PREDICT)}"
        )

    required_first_memberships = {
        "builtin_func": BUILTIN_FUNCTIONS,
        "expression": BUILTIN_FUNCTIONS | {"id"},
        "atom": BUILTIN_FUNCTIONS,
        "value": BUILTIN_FUNCTIONS,
        "condition": BUILTIN_FUNCTIONS,
        "bool_ctrl": BUILTIN_FUNCTIONS,
    }
    for nonterminal, required_symbols in required_first_memberships.items():
        missing = required_symbols - FIRST.get(nonterminal, frozenset())
        if missing:
            raise RuntimeError(
                f"FIRST({nonterminal}) is missing revised built-in terminals: {sorted(missing)}"
            )

    required_predict = {
        88: BUILTIN_FUNCTIONS,
        133: BUILTIN_FUNCTIONS,
        149: {"abs"},
        150: {"len"},
        151: {"pow"},
        152: {"sqrt"},
        187: BUILTIN_FUNCTIONS,
    }
    for production_no, required_symbols in required_predict.items():
        missing = required_symbols - PREDICT.get(production_no, frozenset())
        if missing:
            raise RuntimeError(
                f"PREDICT[{production_no}] is missing revised built-in terminals: {sorted(missing)}"
            )


_validate_tables()
